const MTI_LENGTH = 4;
const BITMAP_MIN_LENGTH = 64;
const BITMAP_MAX_LENGTH = 128;
const PROTOCOL_NAME = "ISO";
const INTERFACE = "6";
const PROTOCOL_VERSION = "0100";
const ISO_8583_VERSION = "1993";
let FORMAT_INDICATOR = "000";

module.exports = {
    MTI_LENGTH,
    BITMAP_MIN_LENGTH,
    BITMAP_MAX_LENGTH,
    PROTOCOL_NAME,
    INTERFACE,
    PROTOCOL_VERSION,
    FORMAT_INDICATOR,
    ISO_8583_VERSION
};